# Autogenerated wrapper script for ONNXRuntime_CUDA_jll for x86_64-linux-gnu-cxx11-cuda+11.3
export libonnxruntime, libonnxruntime_providers_cuda, libonnxruntime_providers_shared, libonnxruntime_providers_tensorrt

using CUDNN_jll
using TensorRT_jll
using Zlib_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("ONNXRuntime_CUDA")
JLLWrappers.@declare_library_product(libonnxruntime, "libonnxruntime.so.1.10.0")
JLLWrappers.@declare_library_product(libonnxruntime_providers_cuda, "libonnxruntime_providers_cuda.so")
JLLWrappers.@declare_library_product(libonnxruntime_providers_shared, "libonnxruntime_providers_shared.so")
JLLWrappers.@declare_library_product(libonnxruntime_providers_tensorrt, "libonnxruntime_providers_tensorrt.so")
function __init__()
    JLLWrappers.@generate_init_header(CUDNN_jll, TensorRT_jll, Zlib_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libonnxruntime,
        "lib/libonnxruntime.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxruntime_providers_cuda,
        "lib/libonnxruntime_providers_cuda.so",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libonnxruntime_providers_shared,
        "lib/libonnxruntime_providers_shared.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxruntime_providers_tensorrt,
        "lib/libonnxruntime_providers_tensorrt.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
